package com.mvpjava.tutorial.model;

import com.mvpjava.tutorial.model.ElectricityProvider;

public class NuclearElectricity extends ElectricityProvider {
	
	public Electricity generateNuclearPower()
	{
		return new Electricity("Electricity generated by nuclear fission!");
	}
		
}
